# COPY-PASTE THIS FILE TO config.py AND FILL IN THE VALUES BELOW.
# config.py FILE SHALL BE IGNORED BY GIT TO PREVENT SECRET LEAK.
CLIENT_ID     =
CLIENT_SECRET = ""
REDIRECT_URI  = "http://localhost:8727"
